"""add parking_lots and slot.lot_id (geospatial)

Revision ID: 411c57ad41de
Revises: ae1cf8b16a07
Create Date: 2026-06-16 14:25:34.321795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411c57ad41de'
down_revision = 'ae1cf8b16a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_parking_slots_lot_id'), ['lot_id'], unique=False)
        batch_op.create_foreign_key('fk_parking_slots_lot_id', 'parking_lots', ['lot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.drop_constraint('fk_parking_slots_lot_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_parking_slots_lot_id'))
        batch_op.drop_column('lot_id')

    op.drop_table('parking_lots')
    # ### end Alembic commands ###
